# Site
#repository: sproogen/resume-theme
favicon: images/favicon.ico

# Personal info
name: Mark Maynard
title: Senior Software Engineer
email: cmaynard@gmail.com
website: github.com/markmaynard/markmaynard.github.io

# Social links
twitter_username: markmaynarddev
github_username:  markmaynard
# dribbble_username: jekyll
# facebook_username: jekyll
# flickr_username: jekyll
# instagram_username: chillwildlife
linkedin_username: charles-maynard-302a728
# pinterest_username: jekyll
# youtube_username: globalmtb
# googleplus_username: +jekyll

# About Section
# about_title: About Me
#about_profile_image: images/profile.jpg
about_content: | # this will include new lines to allow paragraphs
  Hi, my name's Mark and I'm a Senior Senior Software Developer.

  I am most skilled in: <mark>Programming</mark> and <mark>Architecture</mark>

# Projects Section
# projects_title: Projects

# Experience Section
# experience_title: Experience

# Education Section
# educaton_title: Education

# More Section
# more_title: A Little More About Me
more_content: | # this will include new lines to allow paragraphs
  Alongside my interests in software engineering and architecture some of my other interests and hobbies are:
   - Playing Guitar and Ukelele
   - Watching Sports
   - Playing with the kids

# Footer
footer_show_references: true

# Build settings
remote_theme: sproogen/resume-theme

sass:
  sass_dir: _sass
  style: compressed

plugins:
 - jekyll-seo-tag
